# Generated by Django 4.2.20 on 2025-04-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('aadhaar', models.CharField(max_length=12, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('travel_date', models.DateField()),
                ('destination', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
